# Generated by Django 5.1.2 on 2025-04-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
                ('saddr', models.CharField(max_length=20)),
            ],
        ),
    ]
