# Generated by Django 5.1.2 on 2025-05-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studensapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='student',
        ),
    ]
